import type { Metadata } from "next";
import { Geist, Geist_Mono,Quicksand } from "next/font/google";
import "@/ui/globals.css";
import { getAttribute } from '@/lib/data';
import NavBar from "@/ui/homepage/navbar";
import Provider from "@/services/authContext";
export const quicksand = Quicksand({  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // adjust as needed
  variable: '--font-quicksand'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bizora",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let occasions:string[] = [], fit:string[] = [], styles:string[] = [], fabrics:string[] = [];

  try {
    const data = await getAttribute();
    occasions = data.occasions || [];
    fit = data.fit || [];
    styles = data.styles || [];
    fabrics = data.fabrics || [];
  } catch (err) {
    console.error("Navbar data fetch failed:", err);
  }

  return (
    <html lang="en">
      <body>
        <Provider>
          <NavBar occasions={occasions} fit={fit} styles={styles} fabrics={fabrics} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
